### ISSUE TITLE
"Go to definition" doesn't work 

### ISSUE THREAD

**Issue by Jaehaks** [mathworks/MATLAB-language-server#54]
**Describe the bug**
At commit [2245fbe](https://github.com/mathworks/MATLAB-language-server/commit/2245fbecbe4059f692616f868b4d7fc9e61a0d43), `go to definition` works well. 
but after update matlab language server commit [bb6f79e](https://github.com/mathworks/MATLAB-language-server/commit/bb6f79e976b95abe4d767f626744948cf138622e), it doesn't works in neovim

**To Reproduce**
1. update language server the most recent commit
2. do `:lua vim.lsp.buf.definition()`

**Expected behavior**
show definition of function under cursor

**Screenshots**
![image](https://github.com/user-attachments/assets/3c704b3b-862f-45e2-8fc3-7c74cbfb2530)

**Useful Information**
 - OS Version: Windows 10
 - Language Server Client: `nvim-lspconfig` in neovim
 - Client Version: neovim v0.10.2 / nvim-lspconfig commit (87c8c83)

**Additional context**
As I hope, Can you support release version of matlab-language-server?
 I install this server using (mason.nvim)[https://github.com/williamboman/mason.nvim], 
 if I want to install before version, It seems that language server is managed by release.

**Comment by dklilley** [comment]
Thanks for reporting this!

It appears that this has been caused due to a new configuration setting being added to the language server, but this setting is not present in the configuration for Neovim.

We will work to resolve this within the language server (i.e. using default values when the configuration is missing entries) in an upcoming update. In the meantime, this can be worked around by adding the following setting to the configuration for Neovim:
* Name: `maxFileSizeForAnalysis`
* Value: `0`

The value of `0` indicates that there is no size limit for analyzing files.

**Comment by oracleyue** [comment]
If you use 1.2.6, everything works properly. I even failed to install 1.2.7 on NeoVim, with the newest `node`/`npm`. It reports errors in some json files in this version. VS Code can install 1.2.7 but it also failed to work properly, thus I installed 1.2.6. Anyway let us wait for the next version.

PS: Since no release used in github, `mason` cannot specify an older version to install, sigh...

**Comment by Jaehaks** [comment]
@oracleyue 

> Update: now I upgrade node from 23.2.0 to 23.3.0, the matlab lsp has been installed.

I confirm that `v1.2.7` of `matlab_ls` can be installed by `Mason` although it takes long time to install. 

you mean that the lower version can be executed using `npm` after downloading previous commit? I will try it. Thanks

**Comment by oracleyue** [comment]
> I confirm that `v1.2.7` of `matlab_ls` can be installed by `Mason` although it takes long time to install.

Thanks! Now I can also install it with `node 23.3.0`. And I was able to install when I used quite old version node, around 22 or sth. It is just quite strange that `node 23.2.0` on my computer failed to compile the lsp. Anyway, it doesn't matter, maybe a subtle bug in node

> you mean that the lower version can be executed using npm after downloading previous commit? I will try it. Thanks

Yes, `matlab_ls v1.2.6` has not problem to jump and complete. However, `mason` cannot specify the version of matlab lsp to install (since it doesn't really have a release, I guess; maybe just I know little about `mason` and failed to set properly. If you managed to use `mason` to install older version of this lsp, pleeeeease let me know, thanks!!!).

My current temporary fix is to clone this repo to the place of mason lsp, use npm command to compile it and write a script of `matlab-language-server` by myself (as `mason` does) and link it to the bin of mason lsp.

**Comment by dklilley** [comment]
The issue I described above regarding using the default settings when they are missing from the language server configuration has been resolved by v1.3.0 of the language server (#55). I am going to mark this issue as resolved, but please feel free to reopen if the issue around "Go to definition" is still not resolved.
